import type { Metadata } from 'next';

import '@/styles/globals.css';
import { Chat } from '@/modules/Chat';
import Provider from '@/provider';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className="bg-slate-900">
        <Provider>
          <Chat />
          {children}
        </Provider>
      </body>
    </html>
  );
}
